### PR TITLE
Add clang-format to cdt-infra-plus-eclipse-install

### PR DESCRIPTION
**Pull request by T-Svensson**
Signed-off-by: Torbjörn Svensson <azoff@svenskalinuxforeningen.se>

### CODE REVIEW

**Comment by jonahgraham** [comment]
I'll rebuild and push new images now. I'll let you know here when that is done.

**Comment by jonahgraham** [comment]
PS. Does using clang-format mean that https://github.com/eclipse-cdt/cdt-infra/blob/15d06f519b59c70b2a53f2c962fe7195f584834f/docker/cdt-infra-plus-eclipse-install/ubuntu-18.04/Dockerfile#L10-L11 is no longer needed?

**Comment by T-Svensson** [comment]
> PS. Does using clang-format mean that
> 
> https://github.com/eclipse-cdt/cdt-infra/blob/15d06f519b59c70b2a53f2c962fe7195f584834f/docker/cdt-infra-plus-eclipse-install/ubuntu-18.04/Dockerfile#L10-L11
> is no longer needed?

No, it's not needed. See my comment in  https://bugs.eclipse.org/bugs/show_bug.cgi?id=568079.

CDT formatter is not working as expected, and clang-formatter is does more or less what I expect, so I think we should just use it rather than try to fix the CDT formatter. There are so many wired formatting issues with CDT formatter right now.

**Comment by jonahgraham** [comment]
OK - I have pushed the image (without CPP buildtool removed).

Note I had forgotten that where you added the clang-format would not apply to the end result image, so see commit  65fd9ffd3b6ff95c62fb88af0ae4cf4820b4cdb5 for how I ended up adding it.

Let me know what else you need.

**Pull request merged**
