### PR TITLE
Add powerpc cross compile toolchain to docker image

### PR DESCRIPTION
**Pull request by T-Svensson**
Signed-off-by: Torbjörn Svensson <azoff@svenskalinuxforeningen.se>

### CODE REVIEW

**Comment by jonahgraham** [comment]
Based what is in the new packages I see no issue in just adding it to the image. I will build and deploy it now. If it turns out to be useless we can try to remember to remove it!

**Comment by jonahgraham** [comment]
Images are deploying now - but I need to step away from my computer for a bit. If it doesn't fail it should be there (on quay) in a few minutes and I will push to gerrit the new references a little later.

**Comment by T-Svensson** [comment]
I just tried to build using the newly generated image, but it fails.
Maybe the packages are not the right ones...

I googled for a bit more and found these:
g++-powerpc64le-linux-gnu
gcc-powerpc64le-linux-gnu

Do you think they match what we are needing?

I have too little knowledge of the different powerpc's to gasp what the difference is.

**Comment by jonahgraham** [comment]
The powerpc64le looks more promising as that matches the name better - https://git.eclipse.org/r/c/cdt/org.eclipse.cdt/+/138416 is the commit that removed ppc32 and ppc64.

Unless we find a machine to test on, I won't be able to merge the changes. Can you reach out to Mat Booth at redhat to ask him?

**Comment by jonahgraham** [comment]
Done with d2638faea3455f61646f7e3fd870eb7af37a1c3c

**Pull request closed without merging**
